DEATHS = 'DEATHS'
RECOVERIES = 'RECOVERIES'
NEWCASES = 'NEWCASES'
ICU = 'ICU'

TABLES = [DEATHS,RECOVERIES,NEWCASES,ICU]

DISPLAY_NAMES = {DEATHS:'Deaths',RECOVERIES:'Recoveries',NEWCASES:'New Cases',ICU:'ICU'}

SEX = 'SEX'
SNO = 'SNO'
TOT = 'TOT'
PNO = 'PNO'
AGE = 'AGE'
DOA = 'DOA'
DOD = 'DOD'
DPNO = 'DPNO'
PNOS = 'PNOS'
ISOAT = 'ISOAT'
SOURCE = 'SOURCE'
CMRBDTS = 'CMRBDTS'
SYMPTMS = 'SYMPTMS'
DISTRICT = 'DISTRICT'

SUCCESS = '\033[32m' 
ERROR = '\033[31m'