DEATHS = 'DEATHS'
RECOVERIES = 'RECOVERIES'
NEWCASES = 'NEWCASES'
ICU = 'ICU'

TABLES = [DEATHS,RECOVERIES,NEWCASES,ICU]

DISPLAY_NAMES = {DEATHS:'Deaths',RECOVERIES:'Recoveries',NEWCASES:'New Cases',ICU:'ICU'}
